---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: 13.0

verifier:
  name: inspec

platforms:
  - name: windows2012-R2
    driver:
      box: mwrock/Windows2012R2
      gui: false

suites:
  - name: default
    run_list:
      - recipe[manage_chef_client_task::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
